% Import and plot age and BMI data

% Use the function generated by the Import Wizard to load the data
[Age,BMI] = ImportMedData('MedicalData.txt',2,1001);

% Clean the data
badData = isnan(Age)|isnan(BMI);
CleanAge = Age(~badData);
CleanBMI = BMI(~badData);

% Plot as a scatter graph
plot(CleanAge/12,CleanBMI,'o');
xlabel('Age, years');
ylabel('BMI');
title('Age vs BMI');